### ISSUE TITLE
프로세스 비정상 종료시, 포트 점유 문제

### ISSUE THREAD

**Issue by qqaazz0222** [DGU-PoliceLab/System_Integration#3]
# Ctrl + C 또는 오류로 run.py 프로세스 종료 시, Socket Thread에서 포트 점유

다음 실행시, 아래와 같은 오류 발생
```
Exception in thread Thread-1 (run_socket_server):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
server created
Server is starting
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/System_Integration/_Utils/socket_tcp.py", line 8, in run_socket_server
    server.start(port)
  File "/System_Integration/_Utils/socket_tcp.py", line 68, in start
    self.__socket.bind(('localhost', port))
OSError: [Errno 98] Address already in use
Loads checkpoint by local backend from path: _PoseEstimation/mmlab/mmpose/checkpoints/rtmo-l_16xb16-600e_body7-640x640-b37118ce_20231211.pth
06/27 16:04:54 - mmengine - WARNING - Failed to search registry with scope "mmpose" in the "function" registry tree. As a workaround, the current "function" registry in "mmengine" is used to build instance. This may cause unexpected failure when running the built modules. Please check whether "mmpose" is a correct scope, or whether the registry is initialized.
OpenCV: FFMPEG: tag 0x3476706d/'mpv4' is not found (format 'mp4 / MP4 (MPEG-4 Part 14)')'
Traceback (most recent call last):
  File "/System_Integration/run.py", line 170, in <module>
    main()
  File "/System_Integration/run.py", line 117, in main
    socket_provider.start(target=20000)
  File "/System_Integration/_Utils/socket_tcp.py", line 109, in start
    self.__socket.connect(('localhost', target))
ConnectionRefusedError: [Errno 111] Connection refused
Loads checkpoint by local backend from path: _HAR/PLASS/models/selfharm/checkpoint.pth
Exception in thread Thread-3 (Selfharm):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/System_Integration/_HAR/PLASS/selfharm.py", line 85, in Selfharm
    socket_consumer.start(20000) # TCP option
  File "/System_Integration/_Utils/socket_tcp.py", line 160, in start
    self.__socket.connect(('localhost', target))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by qqaazz0222** [comment]
아래 내용 참고
https://priming.tistory.com/59
